#!/usr/bin/env -S deno run --allow-net --allow-env --allow-write
// catalogue.ts (D-835) — EVERY TEST THIS PROGRAMME HAS RUN, IN ONE FILE, GENERATED FROM THE LEDGER.
// The record is 18,000 lines of DECISIONS.md plus a Postgres table; finding "have we tested X, and what decided it"
// meant reading prose. This generates docs/CATALOGUE.md from trd_lineage + trd_prereg + trd_forward_rules so it can
// never drift from the ledger: it is regenerated by the daily runner, not maintained by hand.
// Each row carries the four things a reader actually needs: what was claimed, what decided it, what the verdict was,
// and - where the pre-registration stated one - WHAT WOULD REVERSE IT.
import { declareKnobs, mkStrictRead, assertNonEmpty } from "../supabase/functions/_shared/run-preconditions.ts";
const K = declareKnobs("catalogue", [{ name: "OUT", def: "docs/CATALOGUE.md" }]);
const OWNED = Deno.env.get("OWNED_REST") || "http://localhost:33000"; const SECRET = Deno.env.get("JWT_SECRET")!;
async function jwt() { const e = (o: unknown) => btoa(JSON.stringify(o)).replace(/=/g, "").replace(/\+/g, "-").replace(/\//g, "_"); const h = e({ alg: "HS256", typ: "JWT" }), b = e({ role: "service_role", iss: "cat", exp: 4102444800 }); const k = await crypto.subtle.importKey("raw", new TextEncoder().encode(SECRET), { name: "HMAC", hash: "SHA-256" }, false, ["sign"]); const s = new Uint8Array(await crypto.subtle.sign("HMAC", k, new TextEncoder().encode(`${h}.${b}`))); return `${h}.${b}.${btoa(String.fromCharCode(...s)).replace(/=/g, "").replace(/\+/g, "-").replace(/\//g, "_")}`; }
const hdr = await (async () => { const t = await jwt(); return { Authorization: `Bearer ${t}`, apikey: t }; })();
const { q } = mkStrictRead(OWNED, hdr);
const lin = await q(`trd_lineage?select=id,name,family,status,verdict,key_metric,decision_refs,resolved_at&order=family,id&limit=5000`) as
  { id: string; name: string; family: string; status: string; verdict: string; key_metric: string; decision_refs: string[]; resolved_at: string }[];
const pre = await q(`trd_prereg?select=id,outcome,kill_condition&limit=1000`) as { id: string; outcome: string | null; kill_condition: string }[];
const fwd = await q(`trd_forward_rules?select=id,spec,clock_started,promote_if,kill_if&limit=200`) as { id: string; spec: string; clock_started: string; promote_if: string; kill_if: string }[];
assertNonEmpty("lineage rows", lin, 100);
const killMap = new Map(pre.map((p) => [p.id, p.kill_condition]));
const one = (s: string | null, n = 240) => (s ?? "").replace(/\s+/g, " ").trim().slice(0, n);
const byFam = new Map<string, typeof lin>();
for (const r of lin) (byFam.get(r.family) ?? byFam.set(r.family, []).get(r.family)!).push(r);
const STATUS_ORDER = ["monitoring", "measured", "MEASURED", "confirmed-corrected", "watched", "method-adopted", "fixed", "killed", "rejected", "superseded", "guard-shipped"];
const rank = (s: string) => { const i = STATUS_ORDER.indexOf(s); return i < 0 ? 99 : i; };
let out = `# CATALOGUE — every test this programme has run\n\n`;
out += `> GENERATED by \`scripts/catalogue.ts\` from \`trd_lineage\`, \`trd_prereg\` and \`trd_forward_rules\` — regenerated\n`;
out += `> every day by the runner, never edited by hand, so it cannot drift from the ledger it describes.\n`;
out += `> Generated ${new Date().toISOString().slice(0, 19)}Z · **${lin.length} tests** · ${pre.length} pre-registrations · ${fwd.length} forward clocks.\n\n`;
out += `**How to read a row.** \`status\` is the ledger's own: *monitoring* = live or on a clock; *measured* = a real\n`;
out += `effect quantified but not promotable; *killed / rejected* = closed, with the reason in the verdict; *fixed* = a\n`;
out += `defect in our own machinery, not a market finding. **Nothing here is promoted** — 0 rows have ever been.\n\n`;
out += `## Index\n\n`;
for (const [fam, rows] of [...byFam.entries()].sort((a, b) => b[1].length - a[1].length)) {
  const live = rows.filter((r) => !["killed", "rejected"].includes(r.status)).length;
  out += `- [${fam}](#${fam.replace(/[^a-z0-9]+/gi, "-").toLowerCase()}) — ${rows.length} test(s), ${live} not closed\n`;
}
out += `\n## Forward clocks — the only things that can still change a verdict\n\n`;
out += `| clock | started | promotes if | kills if |\n|---|---|---|---|\n`;
for (const f of fwd.sort((a, b) => a.id < b.id ? -1 : 1)) out += `| \`${f.id}\` | ${f.clock_started} | ${one(f.promote_if, 150)} | ${one(f.kill_if, 150)} |\n`;
for (const [fam, rows] of [...byFam.entries()].sort((a, b) => b[1].length - a[1].length)) {
  out += `\n## ${fam}\n\n`;
  for (const r of rows.sort((a, b) => rank(a.status) - rank(b.status) || (a.id < b.id ? -1 : 1))) {
    out += `### \`${r.id}\` — ${r.status}${r.resolved_at ? ` · ${r.resolved_at}` : ""}\n`;
    out += `**${one(r.name, 200)}**\n\n`;
    out += `- **verdict** — ${one(r.verdict, 500)}\n`;
    if (r.key_metric) out += `- **what decided it** — ${one(r.key_metric, 400)}\n`;
    const kc = killMap.get(r.id);
    if (kc) out += `- **what would reverse it** — ${one(kc, 300)}\n`;
    if (r.decision_refs?.length) out += `- **entries** — ${r.decision_refs.join(", ")}\n`;
    out += `\n`;
  }
}
await Deno.writeTextFile(new URL(`../${K.OUT}`, import.meta.url).pathname, out);
const counts = new Map<string, number>();
for (const r of lin) counts.set(r.status, (counts.get(r.status) ?? 0) + 1);
console.log(`==> CATALOGUE written: ${K.OUT} (${(out.length / 1024).toFixed(0)} KB, ${lin.length} tests across ${byFam.size} families)`);
console.log(`    by status: ` + [...counts.entries()].sort((a, b) => b[1] - a[1]).map(([k, v]) => `${k} ${v}`).join(" · "));
console.log(`    ${fwd.length} forward clocks listed with their promote/kill conditions; ${[...killMap.keys()].length} tests carry a "what would reverse it".`);
if (lin.length < 100 || byFam.size < 5) { console.error("!! POSITIVE CONTROL FAILED — too few rows or families; the catalogue would be silently thin."); Deno.exit(1); }
