#!/usr/bin/env -S deno run --allow-net --allow-env --allow-read
// hypothesis-provenance.ts (D-848) — DESCRIPTIVE ONLY. A self-attack on FLAWS C6 and C7.
//
// C6, named by reasoning and never tested, and the register calls it the most valuable entry in it: 2.9M trials, but
// the SPACE searched is what one person suggested and one model thought of. Every other flaw asks whether a finding
// is wrong. C6 asks whether the right question was ever asked — and no amount of statistical discipline touches it.
// The register's own argument is that the mechanisms which SURVIVED were found accidentally while looking elsewhere.
// That is checkable against the ledger rather than assertable.
//
// C7 rides along because it needs the same classification: post-publication decay is applied to some literature
// signals and not others. A literature-derived test can only be read as "it stopped working" rather than "it never
// worked" if its publication date is known, and this counts how many carry one.
import { declareKnobs, mkStrictRead, assertNonEmpty } from "../supabase/functions/_shared/run-preconditions.ts";
const K = declareKnobs("hypothesis-provenance", [
  { name: "SELFTEST", def: "0", note: "1 = prove each classifier fires on a hand-written example and that the unclassified bucket is not swallowing everything" },
]);
const OWNED = Deno.env.get("OWNED_REST") || "http://localhost:33000"; const SECRET = Deno.env.get("JWT_SECRET")!;
async function jwt() { const e = (o: unknown) => btoa(JSON.stringify(o)).replace(/=/g, "").replace(/\+/g, "-").replace(/\//g, "_"); const h = e({ alg: "HS256", typ: "JWT" }), b = e({ role: "service_role", iss: "hyp", exp: 4102444800 }); const k = await crypto.subtle.importKey("raw", new TextEncoder().encode(SECRET), { name: "HMAC", hash: "SHA-256" }, false, ["sign"]); const s = new Uint8Array(await crypto.subtle.sign("HMAC", k, new TextEncoder().encode(`${h}.${b}`))); return `${h}.${b}.${btoa(String.fromCharCode(...s)).replace(/=/g, "").replace(/\+/g, "-").replace(/\//g, "_")}`; }
const tok = await jwt(); const hdr = { Authorization: `Bearer ${tok}`, apikey: tok };
const { q } = mkStrictRead(OWNED, hdr);

// The classifiers are deliberately CONSERVATIVE: a row that matches nothing goes to UNCLASSIFIED rather than being
// forced into the nearest bucket. A forced classification would make the shares look precise and mean nothing, which
// is the same defect as a fraction of a made-up denominator (D-847).
const CLASS: [string, RegExp, string][] = [
  ["operator", /operator (instruction|asked|said|suggest|direct|challenge)|the operator wants|operator's (question|instruction|standard)/i, "the operator named the question"],
  ["literature", /literature|published|peer.reviewed|\b(Fama|French|Jegadeesh|Corwin|Schultz|Amihud|Novy.Marx|Asness|Douglas|Schwager)\b|the paper|known anomaly|documented (anomaly|stylized|stylised)|stylized fact|stylised fact|academic|classic(al)? (anomaly|result)|longshot bias|momentum anomaly/i, "a published result was the source"],
  ["enumeration", /sweep|enumerat|exhaustive|grammar.search|battery|all \d+ (windows|variants|combinations|cells)|systematic search|frontier/i, "a systematic search over a defined space"],
  ["accident", /found (while|by accident)|discovered while|noticed while|stumbled|came up while|surfaced while|by chance|fell out of|surfaced \w+ at/i, "found while looking at something else"],
  ["self-attack", /flaw c\d|self.attack|methodology_flaws|re-?read my own|audit of (our|my) own|our own (record|method)/i, "an attack on our own method"],
  // THE BUCKET THE FIRST RUN MISSED, and it turned out to be the dominant one. 81% landed unclassified because the
  // classifier was looking for the language of an EXTERNAL source, and most rows here cite a prior D-NNN of this
  // programme's own — "D-627 closed with", "D-603 died because", "the equity VRP survived audit (D-454)". That is a
  // real and specific origin, not an absence of one, and reporting it as unclassified would have hidden C6's answer.
  ["follow-on", /\bD-\d{3}\b|follows? (from|on)|implied by|the test (it|that|which)? ?implied|next step from|prior record|closed with|died because/i, "generated by a previous entry of this programme"],
];

const rows = await q(`trd_lineage?select=id,family,status,hypothesis,test_method,verdict,resolved_at&limit=5000`) as { id: string; family: string; status: string; hypothesis: string; test_method: string; verdict: string; resolved_at: string | null }[];
assertNonEmpty("lineage rows", rows, 100);

console.log(`\n==> D-848 HYPOTHESIS PROVENANCE — flaws C6 and C7. Where did the questions come from?`);
console.log(`    DESCRIPTIVE ONLY. Every other flaw asks whether an answer is wrong. This asks whether the question was ever asked.\n`);

const buckets = new Map<string, string[]>();
for (const [n] of CLASS) buckets.set(n, []);
buckets.set("unclassified", []);
for (const r of rows) {
  const hay = `${r.hypothesis ?? ""} ${r.test_method ?? ""}`;
  const hit = CLASS.filter(([, re]) => re.test(hay)).map(([n]) => n);
  if (!hit.length) buckets.get("unclassified")!.push(r.id);
  else for (const h of hit) buckets.get(h)!.push(r.id);   // a row may have two origins; both are counted and said so
}
console.log(`  ${rows.length} ledger rows classified by ORIGIN (a row with two origins counts in both, so shares sum above 100%):`);
console.log(`  ${"origin".padEnd(14)} ${"rows".padStart(6)} ${"share".padStart(7)}   what it means`);
for (const [n, , what] of CLASS) { const b = buckets.get(n)!; console.log(`  ${n.padEnd(14)} ${String(b.length).padStart(6)} ${(100 * b.length / rows.length).toFixed(1).padStart(6)}%   ${what}`); }
const un = buckets.get("unclassified")!;
console.log(`  ${"unclassified".padEnd(14)} ${String(un.length).padStart(6)} ${(100 * un.length / rows.length).toFixed(1).padStart(6)}%   matched no classifier — NOT forced into the nearest bucket`);

// C6's own argument, checked rather than asserted: are the SURVIVORS disproportionately accidental?
const LIVE = /monitoring|watched|measured|confirmed/i;
const survivors = rows.filter((r) => LIVE.test(r.status ?? ""));
console.log(`\n  C6's OWN ARGUMENT, CHECKED: "the mechanisms that survived were found accidentally while looking elsewhere".`);
console.log(`  ${"origin".padEnd(14)} ${"survivors".padStart(10)} ${"of that origin".padStart(15)} ${"vs base rate".padStart(13)}`);
const baseRate = survivors.length / rows.length;
for (const [n] of CLASS) {
  const b = new Set(buckets.get(n)!);
  const s = survivors.filter((r) => b.has(r.id)).length;
  if (!b.size) continue;
  console.log(`  ${n.padEnd(14)} ${String(s).padStart(10)} ${(100 * s / b.size).toFixed(1).padStart(14)}% ${((s / b.size) / baseRate).toFixed(2).padStart(12)}x`);
}
console.log(`    base rate: ${survivors.length} of ${rows.length} rows are still live (${(100 * baseRate).toFixed(1)}%).`);

// C7: how many literature-derived rows carry a publication date at all?
const lit = new Set(buckets.get("literature")!);
const litRows = rows.filter((r) => lit.has(r.id));
const YEAR = /\b(19[5-9]\d|20[0-2]\d)\b/;
const dated = litRows.filter((r) => YEAR.test(`${r.hypothesis ?? ""} ${r.test_method ?? ""}`.replace(/\b(19|20)\d\d-\d\d(-\d\d)?/g, "")));
console.log(`\n  C7 — post-publication decay needs a publication DATE, and this is how many have one:`);
console.log(`    ${litRows.length} literature-derived rows; ${dated.length} (${(100 * dated.length / Math.max(1, litRows.length)).toFixed(0)}%) name a year that is not a data-span date.`);
console.log(`    Without a date, a null on a published anomaly cannot be read as "it stopped working" rather than "it never worked",`);
console.log(`    and this record has been making that reading selectively. D-843 sharpened the same point from the cost side:`);
console.log(`    every "it decayed" story is a GROSS-return story told against a cost curve that fell 19x.`);

console.log(`\n  WHAT THIS MEASURES AND WHAT IT CANNOT. It measures the stated ORIGIN of questions this programme actually`);
console.log(`  asked. It says nothing about the questions never asked, which is C6's real claim and is unmeasurable by`);
console.log(`  construction — no audit of a search can reveal what was outside it. The honest use of these shares is as a`);
console.log(`  DIVERSITY reading: an origin mix dominated by one source is a search space shaped by one source.`);
if (K.SELFTEST === "1") {
  const cases: [string, string][] = [["operator", "Operator instruction: look at instruments where range is priced directly"],
    ["literature", "the Corwin and Schultz (2012) estimator from the published literature"],
    ["enumeration", "an exhaustive sweep of all 22 possible 2-hour windows"],
    ["accident", "found while re-reading output for something else, discovered while checking a control"],
    ["self-attack", "FLAW C6 of docs/METHODOLOGY_FLAWS.md, a self-attack"],
    ["follow-on", "the test that it implied, following on from D-828"]];
  console.log(`\n  SELFTEST:`);
  let bad = 0;
  for (const [want, txt] of cases) {
    const got = CLASS.filter(([, re]) => re.test(txt)).map(([n]) => n);
    const ok = got.includes(want);
    console.log(`    ${want.padEnd(13)} fires on its own example ... ${ok ? "YES" : "NO"}${got.length > 1 ? `  (also ${got.filter((g) => g !== want).join(",")})` : ""}`);
    if (!ok) bad++;
  }
  const none = CLASS.filter(([, re]) => re.test("a plain measurement of daily ranges on 24 instruments")).length;
  console.log(`    a row with no stated origin stays UNCLASSIFIED ... ${none === 0 ? "YES" : "NO"}`);
  if (bad || none !== 0) { console.error(`!! SELFTEST FAILED — the classifier does not discriminate.`); Deno.exit(1); }
  console.log(`  SELFTEST PASSED — every classifier fires on its own example and none fires on a bare measurement.`);
}
