#!/usr/bin/env -S deno run --allow-net --allow-env --allow-read --allow-write
// question-ledger.ts (D-864) — EVERY QUESTION, ASKED OR NOT, as a grid rather than a feeling. Operator: "we can't have
// any more questions that haven't been asked". A question here is a CELL: horizon x asset class x counterparty
// mechanism (the search-space taxonomy). Each cell is matched to ledger rows by horizon words and mechanism words in
// the row NAME and FAMILY (name+family only — D-850's lesson), and prints ASKED (rows) or UNASKED. The grid is the
// operator's list of what a next design can be; an UNASKED cell is a question never put, not a market shown efficient.
import { declareKnobs, mkStrictRead } from "../supabase/functions/_shared/run-preconditions.ts";
const K = declareKnobs("question-ledger", [{ name: "OUT", def: "docs/QUESTION_LEDGER.md" }]);
const OWNED = Deno.env.get("OWNED_REST") || "http://localhost:33000"; const SECRET = Deno.env.get("JWT_SECRET")!;
async function jwt() { const e = (o: unknown) => btoa(JSON.stringify(o)).replace(/=/g, "").replace(/\+/g, "-").replace(/\//g, "_"); const h = e({ alg: "HS256", typ: "JWT" }), b = e({ role: "service_role", iss: "ql", exp: 4102444800 }); const k = await crypto.subtle.importKey("raw", new TextEncoder().encode(SECRET), { name: "HMAC", hash: "SHA-256" }, false, ["sign"]); const s = new Uint8Array(await crypto.subtle.sign("HMAC", k, new TextEncoder().encode(`${h}.${b}`))); return `${h}.${b}.${btoa(String.fromCharCode(...s)).replace(/=/g, "").replace(/\+/g, "-").replace(/\//g, "_")}`; }
const tok = await jwt(); const { q } = mkStrictRead(OWNED, { Authorization: `Bearer ${tok}`, apikey: tok });
type Row = { id: string; family: string; status: string; name: string };
const rows = await q(`trd_lineage?select=id,family,status,name&limit=5000`) as Row[];
const H: [string, RegExp][] = [["intraday/hourly", /hourly|intraday|\b1h\b|\b5m\b|session|utc|orb|sweep|psl|mtf/i], ["daily", /daily|\bd1\b|overnight|day.open|next.day|\b(k5|k20)\b|event|announcement|filing/i], ["weekly/monthly", /weekly|monthly|\bmonth|week|12m|6m|3m|rebalanc|calendar|seasonal|turn.of|quarter/i], ["multi-year", /decade|century|era|long.run|structural|wrapper|deposit|compound/i]];
const C: [string, RegExp][] = [["crypto", /crypto|perp|btc|eth|binance|bybit|funding|dvol|deribit|spot/i], ["fx", /\bfx\b|eurusd|gbpusd|usdjpy|audusd|carry \(fx\)|currenc/i], ["index/commodity", /index|s&p|spx|nasdaq|nq|es\b|gold|xau|brent|oil|commodit|roll|vix/i], ["equities x-sec", /equit|stock|13f|form 4|insider|ftd|short.interest|ipo|spac|earnings|accrual|factor|momentum|french|pead|sector|etf|cef/i], ["rates/options/other", /rate|yield|option|straddle|skew|implied|vrp|prediction market|bond|tlt/i]];
const M: [string, RegExp][] = [["A forced flows", /index (inclusion|rebalanc)|liquidat|forced|roll|contango|cef|tender|round.up|spac|fails|ftd|tax.loss|window/i], ["B informed/footprint", /insider|congress|13d|13f|n-?port|dark|ats|short (interest|volume)|order.?flow|aggressor|revision|earnings|drift|going.concern|filing/i], ["C insurance/carry", /variance|vrp|straddle|implied|skew|term structure|hedging|cot|tff|carry|lottery|longshot|ipo|prediction/i], ["D slow (trend/reversion/calendar/lead-lag)", /momentum|trend|breakout|mtf|persist|reversal|reversion|fade|exhaust|overnight|season|calendar|day.of.week|settlement|lead.?lag|follower/i], ["E per-head / structural", /bonus|subsid|rebate|prop|payout|class.action|settlement claim|wrapper|isa|sipp|deposit/i], ["F the process itself", /\bhar\b|realised vol|garch|range forecast|vol forecast|atlas|tick|spread estimat|lattice/i]];
const out: string[] = [`# QUESTION LEDGER — every (horizon x class x mechanism) cell, ASKED or UNASKED (D-864)\n`, `> Regenerated by \`scripts/question-ledger.ts\`. A cell is ASKED when at least one ledger row's name or family matches its horizon, class and mechanism words; an UNASKED cell is a question never put to data on this record — not a market shown efficient. ${rows.length} ledger rows.\n`];
let asked = 0, unasked = 0; const unaskedList: string[] = [];
out.push(`| horizon | class | mechanism | rows | status |\n|---|---|---|---|---|`);
for (const [h, hr] of H) for (const [c, cr] of C) for (const [m, mr] of M) {
  const hits = rows.filter((r) => { const t = `${r.name} ${r.family}`; return hr.test(t) && cr.test(t) && mr.test(t); });
  if (hits.length) asked++; else { unasked++; unaskedList.push(`${h} × ${c} × ${m}`); }
  out.push(`| ${h} | ${c} | ${m} | ${hits.length ? hits.slice(0, 3).map((r) => r.id).join(", ") + (hits.length > 3 ? ` +${hits.length - 3}` : "") : "—"} | ${hits.length ? "asked" : "**UNASKED**"} |`);
}
out.splice(2, 0, `**${H.length * C.length * M.length} cells: ${asked} asked, ${unasked} UNASKED.**\n`);
out.push(`\n## The UNASKED cells, as a list\n${unaskedList.map((u) => `- ${u}`).join("\n")}\n\n## How to read it\nKeyword matching is generous on "asked" and strict on "unasked": a cell with rows may still be thin. The unasked list is the honest frontier. Cells that need data the panel does not hold (macro release timestamps, order-book depth, options chains beyond what D-817 collects) are named in docs/WHAT_WE_ARE_MISSING.md.\n`);
await Deno.writeTextFile(new URL(`../${K.OUT}`, import.meta.url).pathname, out.join("\n"));
console.log(`==> QUESTION LEDGER written: ${K.OUT} — ${H.length * C.length * M.length} cells, ${asked} asked, ${unasked} UNASKED`);
for (const u of unaskedList) console.log(`    UNASKED  ${u}`);
