#!/usr/bin/env -S deno run --allow-net --allow-env --allow-read --allow-write
// search-space.ts (D-850) — DESCRIPTIVE ONLY. The one action D-848 licenses.
//
// D-848 measured that 64.1% of this programme's questions were generated by its own previous answers, 1.4% by the
// operator and 5.6% by systematic enumeration — and that enumeration and self-attack are the two origins that yield
// most. A search that mostly asks what its last answer suggested explores a neighbourhood. This file is the
// neighbourhood's map drawn from OUTSIDE it: a fixed taxonomy of WHO PAYS A RETURN AND WHY, written without reference
// to what the ledger already holds, then matched against the ledger so every cell reads TESTED (with its rows) or
// UNTESTED. The taxonomy is mine, not a citation, and is stated as such; its value is that it was not generated by the
// last result. It is regenerated daily so the map cannot silently drift from the record.
import { declareKnobs, mkStrictRead, assertNonEmpty } from "../supabase/functions/_shared/run-preconditions.ts";
const K = declareKnobs("search-space", [{ name: "OUT", def: "docs/SEARCH_SPACE.md" }]);
const OWNED = Deno.env.get("OWNED_REST") || "http://localhost:33000"; const SECRET = Deno.env.get("JWT_SECRET")!;
async function jwt() { const e = (o: unknown) => btoa(JSON.stringify(o)).replace(/=/g, "").replace(/\+/g, "-").replace(/\//g, "_"); const h = e({ alg: "HS256", typ: "JWT" }), b = e({ role: "service_role", iss: "ss", exp: 4102444800 }); const k = await crypto.subtle.importKey("raw", new TextEncoder().encode(SECRET), { name: "HMAC", hash: "SHA-256" }, false, ["sign"]); const s = new Uint8Array(await crypto.subtle.sign("HMAC", k, new TextEncoder().encode(`${h}.${b}`))); return `${h}.${b}.${btoa(String.fromCharCode(...s)).replace(/=/g, "").replace(/\+/g, "-").replace(/\//g, "_")}`; }
const tok = await jwt(); const { q } = mkStrictRead(OWNED, { Authorization: `Bearer ${tok}`, apikey: tok });
type Row = { id: string; family: string; status: string; name: string; hypothesis: string; verdict: string };
const rows = await q(`trd_lineage?select=id,family,status,name,hypothesis,verdict&limit=5000`) as Row[];
assertNonEmpty("lineage rows", rows, 100);

// THE TAXONOMY. Axis: who is on the other side of the trade and why they accept a worse price. Written top-down from
// the counterparty, deliberately NOT from asset class or signal type, because asset class is how this ledger is
// already organised and a map in the ledger's own coordinates finds only what the ledger found.
type Cell = { id: string; who: string; why: string; examples: string; re: RegExp; smallOnly?: boolean };
const T: Cell[] = [
  // A. someone is FORCED to trade
  { id: "A1", who: "index funds", why: "must trade at rebalance regardless of price", examples: "index inclusion/deletion, close auction imbalance, month-end", re: /index (inclusion|rebalanc|add|delet|demotion)|reconstitution|closing auction|auction imbalance|month.end|quarter.end/i },
  { id: "A2", who: "levered holders", why: "margin, liquidation, funding forces the sale", examples: "perp liquidation cascades, funding extremes, forced selling", re: /liquidat|forced sell|margin call|funding (rate|extreme|crowd)|deleverag/i },
  { id: "A3", who: "ETF / ETN / structured wrappers", why: "mechanical roll, leverage reset, creation/redemption", examples: "VIX roll, levered ETF decay, commodity roll, CEF discount", re: /\broll\b|contango|backwardation|levered etf|decay|creation|redemption|cef|closed.end|discount to nav/i },
  { id: "A4", who: "corporate actions", why: "terms fixed by document, not by market", examples: "odd-lot tender, reverse-split round-up, SPAC trust, rights, spin-offs", re: /odd.lot|tender|round.up|reverse split|spac|trust value|rights (issue|offering)|spin.?off|merger arb|cash.out/i, smallOnly: true },
  { id: "A5", who: "regulated / mandated flows", why: "rule requires the trade", examples: "settlement fails, buy-ins, tax-loss selling, window dressing, dividend capture by constrained funds", re: /fails?.to.deliver|ftd|buy.in|tax.loss|window dress|dividend capture|reg sho/i },
  // B. someone is INFORMED and it leaks
  { id: "B1", who: "insiders / politicians", why: "they know first; disclosure lags", examples: "Form 4, congressional, 13D activists", re: /insider|form 4|form345|congress|13d|activist|stock act/i },
  { id: "B2", who: "institutional footprint", why: "size leaves a print", examples: "13F, N-PORT, dark-pool share, ATS, short interest", re: /13f|n-?port|dark.?pool|\bats\b|short interest|short volume|institutional/i },
  { id: "B3", who: "the order book", why: "aggressor imbalance precedes the move (or does not)", examples: "taker imbalance, OI, basis, book depth", re: /aggressor|taker|order.?flow|open interest|\boi\b|basis|depth/i },
  { id: "B4", who: "analysts / issuers", why: "estimates and guidance move before price finishes", examples: "revisions, earnings drift, going-concern, late filings, non-reliance", re: /revision|estimate|earnings|pead|drift|going.concern|late fil|non.?reliance|8-k|auditor/i },
  // C. someone is paying for INSURANCE
  { id: "C1", who: "hedgers", why: "pay a premium to shed variance", examples: "variance risk premium, skew, term structure, hedging pressure (COT/TFF)", re: /variance|vrp|straddle|implied|skew|term structure|hedging pressure|\bcot\b|tff|commercial/i },
  { id: "C2", who: "carry payers", why: "pay to hold the wrong side of a rate gap", examples: "FX carry, funding carry, basis carry, dividend carry", re: /\bcarry\b|interest differential|funding harvest/i },
  { id: "C3", who: "tail buyers", why: "overpay for convexity", examples: "lottery / longshot, low-vol, IPO allocation, prediction markets", re: /lottery|longshot|low.vol|betting against beta|ipo|prediction market|favourite/i },
  // D. someone is SLOW
  { id: "D1", who: "trend followers' counterparties", why: "underreact to persistent information", examples: "time-series momentum, cross-sectional momentum, breakouts, MTF structure", re: /momentum|trend|breakout|\bmtf\b|price.action|persist/i },
  { id: "D2", who: "mean-reverters' counterparties", why: "overreact and pay to get out", examples: "reversal, range exhaustion, fades, overnight/intraday", re: /reversal|reversion|\bfade|exhaust|overreact|overnight/i },
  { id: "D4", who: "cross-instrument laggards", why: "one instrument moves first and the other catches up", examples: "lead-lag, spillover, leader/follower at hourly resolution", re: /lead.?lag|leader|follower|spillover|cross.instrument/i },
  { id: "D3", who: "seasonal / calendar", why: "predictable timing of flows", examples: "turn-of-month, day-of-week, settlement stamps, session windows", re: /season|calendar|day.of.week|turn.of|settlement (clock|stamp)|utc window|session/i },
  // E. someone is SMALL and the venue pays them for it
  { id: "E1", who: "venues / brokers / issuers", why: "subsidise acquisition per HEAD, not per pound", examples: "sign-up bonuses, fee rebates, maker rebates, prop-firm payout structure", re: /bonus|subsid|rebate|acquisition|prop.?firm|payout|referral|cashback/i, smallOnly: true },
  { id: "E2", who: "claims administrators", why: "fixed payment per claimant, most never claim", examples: "class-action settlements, unclaimed elections, abandoned property", re: /class.action|settlement claim|unclaimed|abandon/i, smallOnly: true },
  { id: "E3", who: "the tax and wrapper system", why: "certain, linear, capped per person", examples: "ISA/SIPP wrapper, employer match, deposit compounding", re: /wrapper|\bisa\b|sipp|pension|employer match|deposit/i, smallOnly: true },
  // F. structure of the price process itself
  { id: "F1", who: "nobody — the process", why: "range/vol is forecastable even when direction is not", examples: "HAR-RV, range persistence, GARCH", re: /\bhar\b|har-rv|realised vol|realized vol|garch|range forecast|volatility forecast|vol forecast|atlas/i },
  { id: "F2", who: "nobody — the microstructure", why: "tick, spread, and discreteness", examples: "tick lattice, bid-ask bounce, round numbers, decimalisation", re: /tick|bid.ask|spread estimat|round number|lattice|decimal/i },
];
const out: string[] = [];
out.push(`# SEARCH SPACE — who pays a return and why, mapped against what this programme has actually asked (D-850)\n`);
out.push(`> Regenerated daily by \`scripts/search-space.ts\`. D-848 measured the search as 64.1% self-referential; this map is drawn from OUTSIDE the ledger — by counterparty, not by asset class or signal — and then matched to it. The taxonomy is the author's enumeration, not a citation, and is kept open. **A cell reading UNTESTED is a question this programme has never asked, not a market that has been shown efficient.**\n`);
let tested = 0, untested = 0;
const summary: string[] = [];
for (const c of T) {
  // NAME + FAMILY ONLY. The first run matched hypothesis and verdict text too and reported 19 of 20 cells tested, with
  // 114 rows for range forecasting — because every verdict mentions "range", "structure" or "carry" somewhere. A map
  // that says everything has been asked is the mirror of a false zero, and it is what an inside-drawn map produces.
  const hits = rows.filter((r) => c.re.test(`${r.name} ${r.family}`));
  const live = hits.filter((r) => /monitoring|watched|measured|confirmed/i.test(r.status));
  if (hits.length) tested++; else untested++;
  summary.push(`${c.id} ${hits.length ? `tested ${hits.length} (${live.length} live)` : "UNTESTED"}`);
  out.push(`## ${c.id} — ${c.who}: ${c.why}${c.smallOnly ? "  *(capacity-inverted: pays per head, not per pound)*" : ""}`);
  out.push(`examples: ${c.examples}\n`);
  if (!hits.length) out.push(`**UNTESTED — no ledger row matches this cell.**\n`);
  else {
    out.push(`| row | family | status |\n|---|---|---|`);
    for (const r of hits.slice(0, 12)) out.push(`| ${r.id} | ${r.family} | ${r.status} |`);
    if (hits.length > 12) out.push(`| … | ${hits.length - 12} more | |`);
    out.push("");
  }
}
out.splice(2, 0, `**${T.length} cells: ${tested} have at least one matching row, ${untested} have none.** Cells: ${summary.join(" · ")}\n`);
out.push(`## What this map cannot do\nIt matches by keyword, so a cell with rows may still be badly covered and a cell without rows may have been touched under other words. It is a prompt for the next question, not a certificate. The cells marked capacity-inverted are the only ones where an account near zero holds an advantage (D-834); everything else pays a rate on capital the account does not have.\n`);
await Deno.writeTextFile(new URL(`../${K.OUT}`, import.meta.url).pathname, out.join("\n"));
console.log(`==> SEARCH SPACE written: ${K.OUT} — ${T.length} cells, ${tested} tested, ${untested} UNTESTED`);
for (const s of summary) console.log(`    ${s}`);
